apiVersion: apps/v1
kind: Deployment

metadata:
  name: hub-notification-server-deployment
  #namespace: aks
  labels:
    version: 1.0.0
    product: hub-notification-server
    environment: aks

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-notification-server
      env: aks
  
  template:
    metadata:
      labels:
        app: hub-notification-server
        env: aks
    spec:
      containers:
      - name: signalrservice-container
        image: logcornerhub/logcorner-edusync-notification-server
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Kubernetes.aks"
        ports:
        - containerPort: 80
        - containerPort: 443
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
    
    